os: linux

addons:
  apt:
    # Flutter dependencies
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid

cache:
  directories:
  - "$HOME/flutter/"

before_install:
  - echo $TRAVIS_OS_NAME
  - echo ${HOME}
  - echo ${TRAVIS_BUILD_DIR}
  - if [ ! -d "${HOME}/flutter/bin" ]; then rm -rf ${HOME}/flutter; git clone https://github.com/flutter/flutter.git -b stable --depth 1 ${HOME}/flutter; fi
  - ${HOME}/flutter/bin/flutter doctor
  - ${HOME}/flutter/bin/flutter packages get
  - ${HOME}/flutter/bin/flutter packages pub run build_runner build
  - cd cruzawl
  - ${HOME}/flutter/bin/flutter packages get
  - ${HOME}/flutter/bin/flutter packages pub run build_runner build
  - cd ..

script:
  - ${HOME}/flutter/bin/flutter test

after_success:
  - echo "success"

after_failure:
  - echo "failure"
