name: cruzall
description: Open-source HD wallet for CRUZ cryptocurrency.

version: 1.1.2+22

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  barcode_scan: ^1.0.0
  cruzawl:
    path: ./cruzawl
  cruzawl_ui:
    path: ./cruzawl-ui
  jdenticon_dart: ^1.2.1+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.14.1
  package_info: 0.4.0+6
  path_provider: ^1.2.0
  pedantic: ^1.8.0
  sembast: ^2.0.1
  scoped_model: ^1.0.1
  trust_fall: 1.0.1
  uni_links: ^0.2.0
  url_launcher: ^5.1.1
  url_launcher_fde:
    path: ./desktop/plugins/flutter_plugins/url_launcher_fde

dev_dependencies:
  build_runner: ^1.4.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  screenshots: ^2.0.2+1
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: MartelSans
      fonts:
        - asset: fonts/MartelSans/MartelSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/MartelSans/MartelSans-Light.ttf
          weight: 300
        - asset: fonts/MartelSans/MartelSans-Regular.ttf
          weight: 400
        - asset: fonts/MartelSans/MartelSans-SemiBold.ttf
          weight: 600
        - asset: fonts/MartelSans/MartelSans-Bold.ttf
          weight: 700
        - asset: fonts/MartelSans/MartelSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/MartelSans/MartelSans-Black.ttf
          weight: 900
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900

