name: cruzall
description: The original cruzbit wallet.

version: 1.1.0+20

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  barcode_scan: ^1.0.0
  charts_flutter: ^0.6.0
  clippy: ^1.0.0
  cruzawl:
    path: ./cruzawl
  json_annotation: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gradient_app_bar: ^0.0.1
  package_info: 0.4.0+6
  path_provider: ^1.2.0
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
  sembast: ^2.0.1
  scoped_model: ^1.0.1
  syntax_highlighter: ^0.1.0
  trust_fall: ^1.0.1
  tuple: ^1.0.2
  tweetnacl: ^0.3.2
  url_launcher: ^5.1.1
  url_launcher_fde:
    path: ../cruzall-desktop/plugins/flutter_plugins/url_launcher_fde

dev_dependencies:
  build_runner: ^1.4.0
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: MartelSans
      fonts:
        - asset: fonts/MartelSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/MartelSans-Light.ttf
          weight: 300
        - asset: fonts/MartelSans-Regular.ttf
          weight: 400
        - asset: fonts/MartelSans-SemiBold.ttf
          weight: 600
        - asset: fonts/MartelSans-Bold.ttf
          weight: 700
        - asset: fonts/MartelSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/MartelSans-Black.ttf
          weight: 900

    - family: Roboto
      fonts:
        - asset: desktop/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: desktop/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: desktop/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: desktop/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: desktop/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: desktop/fonts/Roboto/Roboto-Black.ttf
          weight: 900

